### ISSUE TITLE
Critical Issue: Backpacks no longer obeying world-settings

### ISSUE THREAD

**Issue by mrcoffee1026** [TheBusyBiscuit/DyedBackpacks#7]
## Description (Required)
Backpacks working in worlds where this item should be disabled.  All backpacks also disabled in same world, dyed backpacks get a bypass since not following any of these directives.

## Steps to reproduce the Issue (Required)
Example world setting file from creative world:
```
slimefun:
  enabled: false
  GRANDMAS_WALKING_STICK: false
  GRANDPAS_WALKING_STICK: false
  PORTABLE_CRAFTER: false
  FORTUNE_COOKIE: false
  ENHANCED_CRAFTING_TABLE: false
  PORTABLE_DUSTBIN: false
  BEEF_JERKY: false

```
-truncated-
```
dyedbackpacks:
  enabled: false
  DYED_SMALL_BACKPACK_WHITE: false
  DYED_SMALL_BACKPACK_ORANGE: false
  DYED_SMALL_BACKPACK_MAGENTA: false
  DYED_SMALL_BACKPACK_LIGHT_BLUE: false
  DYED_SMALL_BACKPACK_YELLOW: false
  DYED_SMALL_BACKPACK_LIME: false
  DYED_SMALL_BACKPACK_PINK: false
  DYED_SMALL_BACKPACK_DARK_GRAY: false
  DYED_SMALL_BACKPACK_LIGHT_GRAY: false
  DYED_SMALL_BACKPACK_CYAN: false
  DYED_SMALL_BACKPACK_PURPLE: false
  DYED_SMALL_BACKPACK_BLUE: false
  DYED_SMALL_BACKPACK_BROWN: false
  DYED_SMALL_BACKPACK_GREEN: false
```
-- also truncated, but you get the idea -- 

## Expected behavior (Required)
Backpacks should not be openable in that creative world but... THEY ARE.  So people just save a creative toolbar with their dyed backpacks in them and can then save creative inventories into them which they can then later access in any survival world where these backpacks are already enabled.  Wonderful game breaking duplication at their leisure.  I would  like to not have to completely disable this addon thereby deleting these inventories for everyone, but if there is not a fix for this like YESTERDAY, this is the only course of action to take. 

## Server Log / Error Report
No errors, I only wish there were.

## Environment (Required)
[16:53:26 INFO]: Paper v1_16_R3
[16:53:26 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[16:53:26 INFO]: Slimefun vDEV - 743 (git 0b9ab8b6)
[16:53:26 INFO]: Metrics build: #17
[16:53:26 INFO]:
[16:53:26 INFO]: Installed Addons: (27)
[16:53:26 INFO]:  GlobalWarming vDEV - 4 (git bd8e730a)
[16:53:26 INFO]:  SlimyPowerSuits vDEV - 8 (git a93bd3ae)
[16:53:26 INFO]:  ExtraTools vDEV - 22 (git ea11f88b)
[16:53:26 INFO]:  FoxyMachines vDEV - 7 (git 85598948)
[16:53:26 INFO]:  SlimefunOreChunks vDEV - 9 (git 88dd72b0)
[16:53:26 INFO]:  SensibleToolbox vDEV - 31 (git 6b66751d)
[16:53:26 INFO]:  ExtraGear vDEV - 12 (git 4570ea2c)
[16:53:26 INFO]:  MoreTools vDEV - 8 (git db8d8814)
[16:53:26 INFO]:  InfinityExpansion vDEV - 42 (git 85149715)
[16:53:26 INFO]:  SFCalc vDEV - 13 (git 9b3157b4)
[16:53:26 INFO]:  ElectricSpawners vDEV - 18 (git f9da206b)
[16:53:26 INFO]:  ExtraHeads vDEV - 17 (git 6c77b605)
[16:53:26 INFO]:  MobCapturer vDEV - 11 (git 4edf38dd)
[16:53:26 INFO]:  SlimyTreeTaps vDEV - 15 (git 205f8afc)
[16:53:26 INFO]:  PrivateStorage vDEV - 14 (git 98a31c90)
[16:53:26 INFO]:  TranscEndence vDEV - 21 (git f7bb1376)
[16:53:26 INFO]:  FluffyMachines vDEV - 44 (git 716f15e9)
[16:53:26 INFO]:  CMI v8.7.10.5
[16:53:26 INFO]:  ChestTerminal vDEV - 37 (git 5da77284)
[16:53:26 INFO]:  DyedBackpacks vDEV - 9 (git c42435c1)
[16:53:26 INFO]:  SoundMuffler vDEV - 17 (git 3abf8993)
[16:53:26 INFO]:  EcoPower vDEV - 2 (git b0c0c875)
[16:53:26 INFO]:  HotbarPets vDEV - 31 (git 5909202f)
[16:53:26 INFO]:  SlimefunLuckyBlocks vDEV - 29 (git db79cb7c)
[16:53:26 INFO]:  ExoticGarden vDEV - 61 (git b5067266)
[16:53:26 INFO]:  LiteXpansion vDEV - 96 (git cb307aae)
[16:53:26 INFO]:  SoulJars vDEV - 17 (git 9eedba0f)
